# the first stage of our build will use a maven 3.6.1 parent image
# FROM maven:3.6.1-jdk-8-alpine AS MAVEN_BUILD

# copy the pom and src code to the container
# COPY ./ ./

# package our application code
# RUN mvn clean package

# the second stage of our build will use open jdk 8 on alpine 3.9
FROM registry.access.redhat.com/quarkus/mandrel-20-rhel8

# copy only the artifacts we need from the first stage and discard the rest
# COPY --from=MAVEN_BUILD /sub/target/knative-kafka-quarkus-prices-sub-1.0.0-SNAPSHOT-native-image-source-jar/knative-kafka-quarkus-prices-sub-1.0.0-SNAPSHOT-runner.jar /sub.jar
COPY /sub/target/knative-kafka-quarkus-prices-sub-1.0.0-SNAPSHOT-native-image-source-jar/knative-kafka-quarkus-prices-sub-1.0.0-SNAPSHOT-runner.jar /sub.jar

# set the startup command to execute the jar
CMD ["java", "-jar", "/sub.jar"]