apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sink
  namespace: knative-kafka-quarkus-example
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: "2"
        # autoscaling.knative.dev/maxScale: "30"
    spec:
      containers:
       - image: docker.io/aliok/request-logger
         env:
         - name: LATENCY
           value: "100"
