apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: prices
  labels:
      strimzi.io/cluster: my-cluster
spec:
  replicas: 3
  partitions: 12
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prices-app
  name: prices-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prices-app
  template:
    metadata:
      labels:
        app: prices-app
    spec:
      containers:
      - name: prices-app
        image: image-registry.openshift-image-registry.svc:5000/knative-kafka-quarkus-example/knative-kafka-quarkus-example:1.0.0-SNAPSHOT
        env:
          - name: BOOTSTRAP_SERVERS
            value: my-cluster-kafka-bootstrap.kafka:9092
          - name: TOPIC
            value: quickstart-kafka-topic
          - name: DELAY_MS
            value: "1000"
          - name: LOG_LEVEL
            value: "INFO"
          - name: MESSAGE_COUNT
            value: "1000000"
