apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: kafkasource
  namespace: knative-kafka-quarkus-example
spec:
  consumerGroup: knative-group
  bootstrapServers:
  - my-cluster-kafka-bootstrap.kafka:9092
  topics:
  - quickstart-kafka-topic
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: knative-kafka-quarkus-example
