apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-smasher
  namespace: knative-kafka-quarkus-example
spec:
  template:
    spec:
      containers:
      - name: kafka-smasher
        image: docker.io/aliok/kafka-smasher:latest
        env:
          - name: KAFKA_HOST
            value: my-cluster-kafka-bootstrap.kafka:9092
          - name: KAFKA_TOPIC
            value: kafkasource-quickstart
          - name: MESSAGE_COUNT
            value: '20000'
          - name: MESSAGE_FREQUENCY
            value: '0'
      restartPolicy: Never
