apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: prices
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 100
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: data
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 100
  replicas: 1
