apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: prices
  namespace: knative-kafka-quarkus-example
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 100
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: my-data-stream
  namespace: knative-kafka-quarkus-example
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 100
  replicas: 1
