apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: ks-prices-pub
  namespace: knative-kafka-quarkus-example
spec:
  # consumerGroup: knative-group
  bootstrapServers:
  - my-cluster-kafka-bootstrap.kafka:9092
  topics:
  - generated-price
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: prices-pub
    # uri: /process
---
apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: ks-prices-sub
  namespace: knative-kafka-quarkus-example
spec:
  # consumerGroup: knative-group
  bootstrapServers:
  - my-cluster-kafka-bootstrap.kafka:9092
  topics:
  - my-data-stream
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: prices-sub
    # uri: /prices
---
# This one is not needed for topics but as it sends to the first, it keeps them from shutting down.
apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: ks-prices-gen
  namespace: knative-kafka-quarkus-example
spec:
  # consumerGroup: knative-group
  bootstrapServers:
  - my-cluster-kafka-bootstrap.kafka:9092
  topics:
  - prices
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: prices-gen
    # uri: /prices
---
